export const CREATE_FORM_REQUEST = "CREATE_FORM_REQUEST";
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const CREATE_FORM_ERROR = "CREATE_FORM_ERROR";

export const FETCH_FORM_REQUEST = "FETCH_FORM_REQUEST";
export const FETCH_FORM_SUCCESS = "FETCH_FORM_SUCCESS";
export const FETCH_FORM_ERROR = "FETCH_FORM_ERROR";
